apiVersion: apps/v1
kind: Deployment
metadata:
  name:  MYSQL
  namespace: default
  labels:
    app:  MYSQL
spec:
  selector:
    matchLabels:
      app: MYSQL
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  MYSQL
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  MYSQL
        image:  mysql:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 1Gi
        
        ports:
        - containerPort:  3306
          name:  MYSQL

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: mysql
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: "1234"

        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: MYSQL
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306