apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsdeploy
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: "bitnami/jenkins:latest"
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 500m
        #     memory: 1Gi
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: JENKINS_USERNAME
          value: admin

---

piVersion: v1
kind: Service
metadata:
  name: JenkinsService
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jenkins
  ports:
    - name: HTTP
      port: 80
      targetPort: http
      nodePort: 30007
