apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: bitnami/jenkins:latest
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 500m
        #     memory: 1Gi
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: JENKINS_USERNAME
          value: admin

