apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: nanajanashia/argocd-app:1.2
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 500m
        #     memory: 1Gi
        ports:
        - containerPort: 80
        env:
        - name: mydb_HOST
          value: mydb-service
        - name: mydb_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: mydb_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: user
        - name: mydb_PASSWORD
          value: "1234"
