apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mydb
  namespace: default
  labels:
    app:  mydb
spec:
  selector:
    matchLabels:
      app: mydb
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mydb
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  mydb
        image:  mysql
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 500m
        #     memory: 1Gi
        
        ports:
        - containerPort:  3306
          name:  mydb

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: mydb_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: user
        - name: mydb_PASSWORD
          value: "1234"

        # volumeMounts:
        #   - name: mydb-persistent-storage
        #     mountPath: /var/lib/mydb
        # volumes:
        # - name: mydb-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: mydb-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: mydb-service
spec:
  selector:
    app: mydb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306