apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
  matchLabels:
    app: jenkins
  ports:
    - name: HTTP
      port: 80
      targetPort: http
      nodePort: 30007
